swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    x-swagger-router-controller: homepage
    get:
      operationId: homepage
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: Success
          schema:
            type: string
  /material.css:
    x-swagger-router-controller: homepage
    get:
      operationId: material_css
      produces:
        - text/css; charset=utf-8
      responses:
        200:
          description: Success
          schema:
            type: string
  /libs/{folder}/{name}:
    x-swagger-router-controller: libs
    get:
      operationId: fileserve
      description: return selected files
      parameters:
        - name: folder
          type: string
          in: path
          required: true
        - name: name
          type: string
          in: path
          required: true
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: Success
          schema:
            type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /singleExpense/{id}:
    x-swagger-router-controller: expense
    get:
      description: Returns the game itself
      operationId: singleExpense
      parameters:
        - name: id
          type: string
          in: path
          required: true
      produces:
        - text/html; charset=utf-8
      responses:
       200:
        description: Success
        schema:
          type: string
  /expense:
    x-swagger-router-controller: expense
    get:
      operationId: expensesList
      description: Get list of all images.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ExpensesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: createExpense
      description: bla
      consumes:
        - multipart/form-data
      parameters:
        - name: id
          description: id.
          type: string
          required: false
          in: formData
        - name: expenseValue
          description: wartosc
          type: string
          required: false
          in: formData
        - name: date
          description: date.
          type: string
          required: false
          in: formData
        - name: currencyShort
          description: currencyShort.
          type: string
          required: false
          in: formData
        - name: categoryName
          description: categoryName.
          type: string
          required: false
          in: formData
        - name: expenseDescription
          description: desc.
          type: string
          required: false
          in: formData
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ExpenseResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /removeExpense/{id}:
    x-swagger-router-controller: expense
    get:
      operationId: removeSingleExpense
      description: Get expense with selected id
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OperationStatus"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /categories:
    x-swagger-router-controller: category
    get:
      operationId: categories
      description: Get list of all categories.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CategoriesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /manageCategories:
    x-swagger-router-controller: category
    get:
      operationId: manageCategories
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: Success
          schema:
            type: string          
  /currencies:
    x-swagger-router-controller: currency
    get:
      operationId: currencies
      description: Get list of all categories.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CurrenciesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /confimExpense:
    x-swagger-router-controller: expense
    get:
      operationId: confirmExpense
      description: Get list of all categories.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CurrenciesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ExpensesListResponse:
    properties:
      expenses:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            expenseValue:
              type: number
            expenseDate:
              type: string
              format: date-time
            expenseDescription:
              type: string
            expenseCurrencyId:
              type: string
            expenseCategoryId:
              type: string
            expenseMonthId:
              type: string
  ExpenseResponse:
    type: object
    properties:
      id:
        type: string
      expenseValue:
        type: number
      expenseDate:
        type: string
        format: date-time
      expenseDescription:
        type: string
      expenseCurrencyId:
        type: string
      expenseCategoryId:
        type: string
      expenseMonthId:
        type: string
  CategoriesListResponse:
    properties:
      expenses:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            categoryName:
              type: string
            categoryPriority:
              type: number
  CurrenciesListResponse:
    properties:
      expenses:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            currencyName:
              type: string
            currencyShort:
              type: number
  OperationStatus:
    type: object
    properties:
      id:
        type: string
      status:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
